from .user_register import *
from .index import *
from .login import *
from .movie_register import *
from .add_movie import *
from .logout import *
from .my_favorite_movies import *
from .get_users import *
from .get_movie import *
from .update_movie import *
from .get_profile_user import *
from .update_user import *
