# Generated by Django 3.2 on 2023-02-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_repositorymovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='', max_length=500, verbose_name='Gênero'),
        ),
    ]
