# Generated by Django 3.2 on 2023-02-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(blank=True, default='2000-01-01', verbose_name='Data de lançamento'),
        ),
    ]
