# Generated by Django 3.2 on 2023-02-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_movie_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepositoryMovies',
        ),
    ]
